import Foundation

struct SafetyDecision: Equatable, Sendable {
    var classification: SafetyClassification
    var reason: String
}

protocol SafetyClassifying: Sendable {
    func classify(item: StorageItem, configuration: StorageScanConfiguration, now: Date) -> SafetyDecision
}

struct DefaultSafetyPolicy: SafetyClassifying {
    func classify(item: StorageItem, configuration: StorageScanConfiguration, now: Date) -> SafetyDecision {
        if item.isPinned {
            return SafetyDecision(
                classification: .keep,
                reason: "This item is pinned and excluded from cleanup.")
        }

        if item.isIgnored {
            return SafetyDecision(
                classification: .keep,
                reason: "This item is ignored and excluded from cleanup.")
        }

        if item.isActive {
            return SafetyDecision(
                classification: .keep,
                reason: "This item appears active and is excluded from cleanup.")
        }

        let stale = isStale(item: item, now: now, staleAgeDays: configuration.staleAgeDays)
        let codexAttributed = item.attribution == .codex || item.attribution == .xcodeViaCodex
        let unavailableSimulator = item.metadata["isAvailable"] == "false"

        switch item.domain {
        case .coreSimulatorDevices:
            if unavailableSimulator {
                return SafetyDecision(classification: .safeToTrash, reason: "Unavailable simulator devices can be recreated by Xcode.")
            }
            if codexAttributed && isStale(item: item, now: now, staleAgeDays: configuration.keepSimulatorsUsedWithinDays) {
                return SafetyDecision(
                    classification: .probablySafe,
                    reason: "This stale simulator was attributed to Codex-driven Xcode work, but its app data should be reviewed before an explicit simctl action.")
            }
            if stale {
                return SafetyDecision(classification: .probablySafe, reason: "This shutdown simulator is stale, but review its app data before removal.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "Simulator devices may contain app data you might want to inspect first.")
        case .xcTestDevices:
            if codexAttributed || isStale(item: item, now: now, staleAgeDays: configuration.staleXCTestDeviceDays) {
                return SafetyDecision(classification: .safeToTrash, reason: "Stale XCTest device data is generated by test runs and can be recreated.")
            }
            return SafetyDecision(classification: .probablySafe, reason: "Recent XCTest device data is usually rebuildable, but should be reviewed first.")
        case .xcResults:
            if item.metadata["protectedByKeepLastTestRuns"] == "true" {
                return SafetyDecision(classification: .reviewRecommended, reason: "This result bundle is protected by the keep-last-test-runs rule.")
            }
            if codexAttributed || isStale(item: item, now: now, staleAgeDays: configuration.staleXCResultDays) {
                return SafetyDecision(classification: .safeToTrash, reason: "Old result bundles contain diagnostics from past test runs.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "Recent result bundles may still be useful for debugging.")
        case .derivedData:
            if item.attribution == .xcodeViaCodex && stale {
                return SafetyDecision(classification: .safeToTrash, reason: "This stale DerivedData folder was likely created during Codex-driven builds.")
            }
            if stale {
                return SafetyDecision(classification: .probablySafe, reason: "DerivedData is rebuildable, but deleting it can slow the next build.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "DerivedData is usually rebuildable, but deleting it can make the next build slower.")
        case .codexHome:
            if isCodexEphemeralName(item.displayName), stale || codexAttributed {
                return SafetyDecision(classification: .safeToTrash, reason: "Codex cache, temporary, and log folders are safe cleanup candidates.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "Codex history may be useful for resuming or auditing previous work.")
        case .codexWorkspaces:
            if isStale(item: item, now: now, staleAgeDays: configuration.staleCodexWorkspaceDays) && codexAttributed {
                return SafetyDecision(classification: .safeToTrash, reason: "This stale Codex workspace can be moved to Trash after confirmation.")
            }
            if stale {
                return SafetyDecision(classification: .probablySafe, reason: "This Codex workspace is stale, but may contain user-facing deliverables.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "Codex workspaces may contain user-facing deliverables or active project files.")
        case .coreSimulatorCaches:
            if stale || codexAttributed {
                return SafetyDecision(classification: .safeToTrash, reason: "CoreSimulator cache data is generated and can be recreated.")
            }
            return SafetyDecision(classification: .probablySafe, reason: "Simulator caches are rebuildable, but recent entries should be reviewed.")
        case .swiftPackageCaches:
            if stale && codexAttributed {
                return SafetyDecision(classification: .probablySafe, reason: "SwiftPM caches are rebuildable but can slow future package resolution.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "SwiftPM caches are shared across projects and should be reviewed before cleanup.")
        case .xcodeProducts:
            if stale && codexAttributed {
                return SafetyDecision(classification: .safeToTrash, reason: "This stale product artifact was likely generated during Codex-driven builds.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "Xcode Products may contain build outputs or diagnostics you still need.")
        case .archives:
            if configuration.neverTouchArchives {
                return SafetyDecision(classification: .reviewRecommended, reason: "Archives are excluded by the never-touch-archives rule.")
            }
            return SafetyDecision(classification: .reviewRecommended, reason: "Archives can contain signed builds, dSYMs, and distribution metadata.")
        case .deviceSupport:
            return SafetyDecision(classification: .reviewRecommended, reason: "This data may be needed for distribution, symbolication, or device debugging.")
        case .simulatorRuntimes, .simulatorImages:
            return SafetyDecision(classification: .keep, reason: "Simulator runtimes are large, but removing them can break simulator availability.")
        }
    }

    private func isStale(item: StorageItem, now: Date, staleAgeDays: Int) -> Bool {
        guard let date = item.lastActivityAt else {
            return false
        }
        return now.timeIntervalSince(date) >= Double(staleAgeDays) * 24 * 60 * 60
    }

    private func isCodexEphemeralName(_ name: String) -> Bool {
        let lowered = name.lowercased()
        return lowered == "cache" ||
            lowered == "caches" ||
            lowered == "tmp" ||
            lowered == "temp" ||
            lowered == ".tmp" ||
            lowered == "logs" ||
            lowered == "log" ||
            lowered == "debug" ||
            lowered == "shell-snapshots" ||
            lowered == "shell_snapshots" ||
            lowered == "paste-cache" ||
            lowered == "image-cache"
    }
}
